import Head from 'next/head'
import Image from 'next/image'
import Featured from '../components/Featured'
import FeaturedProp from '../components/FeaturedProp'
import Header from '../components/Header'
import MailList from '../components/MailList'
import PropertyList from '../components/PropertyList'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {/* Home Container */}
      <div className="flex flex-col items-center w-full mt-10">
        <Featured />
        <h1 className="text-3xl py-10 font-semibold">Browse by property type</h1>
        <PropertyList />
        <h1 className="text-3xl py-10 font-semibold">Homes guests love</h1>
        <FeaturedProp />
        <MailList />
      </div>

      
    </div>
  )
}
